[package]
name = "uwf-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "uwf"
path = "src/main.rs"

[dependencies]
uwf-core = { path = "../Core" }
uwf-unrealmaster = { path = "../UnrealMaster" }

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
